//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TreinamentoAspNet02.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Atendimentos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Atendimentos()
        {
            this.Mensagens = new HashSet<Mensagens>();
        }
    
        public int Id { get; set; }
        public string Id_Consultor { get; set; }
        public Nullable<int> Id_Visitante { get; set; }
        public bool Encerrado { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public Nullable<int> Duracao { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Visitante Visitante { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mensagens> Mensagens { get; set; }
    }
}
