//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TreinamentoAspNet02.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mensagens
    {
        public int Id { get; set; }
        public string Mensagem { get; set; }
        public string Arquivo { get; set; }
        public string enviadoPorConsultor { get; set; }
        public Nullable<int> enviadoPorVisitante { get; set; }
        public Nullable<int> Id_Atendimento { get; set; }
    
        public virtual Atendimentos Atendimentos { get; set; }
    }
}
